name:                warpleak
version:             0.1.0.0
github:              "koterpillar/warpleak"
license:             BSD3
author:              "Alexey Kotlyarov"
maintainer:          "a@koterpillar.com"
copyright:           "2017 Alexey Kotlyarov"

synopsis:            Short description of your package
description:         Please see the README on Github at <https://github.com/koterpillar/warpleak#readme>

dependencies:
- base >= 4.7 && < 5
- http-types
- wai
- warp

executables:
  warpleak:
    main:                warpleak.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
